---
collections:
- name: effectivelywild.technitium_dns
  version: "1.1.2"
- name: infisical.vault
  version: "1.2.0"
- name: artis3n.tailscale
  version: "1.2.0"
- name: containers.podman
  version: "1.18.1"
